const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const WWW_DIR = path.resolve(__dirname, 'www'); // Shell is now in core/www
const PLUGINS_DIR = path.resolve(ROOT, 'plugins');
const GENERATED_DIR = path.resolve(WWW_DIR, 'src/generated');
const LINKED_PLUGINS_DIR = path.resolve(WWW_DIR, 'src/plugins');

if (!fs.existsSync(GENERATED_DIR)) fs.mkdirSync(GENERATED_DIR, { recursive: true });
if (!fs.existsSync(LINKED_PLUGINS_DIR)) fs.mkdirSync(LINKED_PLUGINS_DIR, { recursive: true });

function scanPlugins(dir) {
    const results = [];
    const entries = fs.readdirSync(dir, { withFileTypes: true });

    for (const entry of entries) {
        if (entry.isDirectory()) {
            const fullPath = path.join(dir, entry.name);
            const wwwPath = path.join(fullPath, 'www');
            
            if (fs.existsSync(wwwPath)) {
                results.push({
                    name: entry.name,
                    path: wwwPath,
                    relativePath: path.relative(ROOT, wwwPath)
                });
            } else {
                results.push(...scanPlugins(fullPath));
            }
        }
    }
    return results;
}

const foundPlugins = scanPlugins(PLUGINS_DIR);
console.log(`Found ${foundPlugins.length} plugins with UI:`, foundPlugins.map(p => p.name).join(', '));

// Create Registry File
let registryContent = `// Generated by scripts/ui-linker.js
import React from 'react';

export const PLUGIN_COMPONENTS: Record<string, React.ComponentType<any>> = {
`;

foundPlugins.forEach(p => {
    // Create Symlink for easy importing
    const symlinkPath = path.join(LINKED_PLUGINS_DIR, p.name);
    if (fs.existsSync(symlinkPath)) fs.unlinkSync(symlinkPath);
    fs.symlinkSync(p.path, symlinkPath, 'dir');

    // Add to registry (using relative path or symlink path)
    registryContent += `  '${p.name}': React.lazy(() => import('../plugins/${p.name}/src/entry')),\n`;
});

registryContent += `};\n`;

fs.writeFileSync(path.join(GENERATED_DIR, 'plugin-registry.ts'), registryContent);
console.log('Registry generated in www/src/generated/plugin-registry.ts');
